- name: check if nodejs installed
  stat:
    path: /usr/local/bin/node
  register: nodejs_bin

- name: yum node dep resolve
  shell: |
    curl -sL https://rpm.nodesource.com/setup_8.x | bash -

- name: temporary install nodejs using yum
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - nodejs
  when: not nodejs_bin.stat.exists

- name: install n using npm
  npm:
    name: n
    state: present
    global: yes
  when: not nodejs_bin.stat.exists

- name: install nodejs using n
  shell: |
    n {{ nodejs_version }}
  when: not nodejs_bin.stat.exists

- name: refresh shell variables to enable npm
  shell: |
    exec $SHELL
  when: not nodejs_bin.stat.exists

- name: set global npm path
  template:
    src: 201_nodejs.sh
    dest: ~/.bash.d/201_nodejs.sh
    mode: 0755
  become_user: "{{ working_user }}"
  when: not nodejs_bin.stat.exists

- name: install yarn using npm
  npm:
    name: yarn
    state: present
    global: yes

- name: yarn install
  shell: |
    yarn install
